### PR TITLE
Update to 0.9.15

### PR DESCRIPTION
**Pull request by rhart**
I'm not entirely sure how this is intended to work so I may have broken something, but all the tests are passing.  What's interesting is that I didn't actually need a Spring backed registry.

If you add more tests for anything that's broken then I'm happy to help try and resolve them.

### CODE REVIEW

**Comment by dsyer** [comment]
Awesome, thanks! The CLI doesn't quite work for some reason I'll have to look into, but that got me a lot further than I was going on my own.

**Comment by rhart** [comment]
I didn't make the launch changes so am not totally au fait with them but glad it's of some help.

Whilst what I've done works, I suspect a `context.get(MySpringBean)` wouldn't work because there's no registry backed by Spring in my changes.  I will add a test and fix this.  

I think there's something we can do better property wise too.  Recent changes mean we can now consume properties from various sources, I wonder whether a Spring `Environment` could be one of them

**Comment by rhart** [comment]
New test added and Spring backed registry joined to Guice registry

**Comment by dsyer** [comment]
Thanks. That works. There are still some things not working (cli and 404 handler), but I've merged onto master anyway.

**Pull request closed without merging**
